---

driver:
  name: docker
  use_sudo: false

provisioner:
  deprecations_as_errors: true

verifier:
  name: inspec

# Customize the following sections for the platforms & suites specific to your cookbook! This is just an example

platforms:
- name: centos-6
  driver:
    image: centos:6

- name: centos-7
  driver:
    image: centos:7

- name: fedora-latest
  driver:
    image: fedora:latest
    
suites:
  - name: default
    run_list:
      - recipe[yum::default]
      - recipe[yum_test::test_globalconfig_two]
    excludes: fedora-latest
  - name: dnf_compat
    run_list:
      - recipe[yum::dnf_yum_compat]
      - recipe[yum_test::test_dnf_compat]
    includes: fedora-latest
    
    
